-- ============================================================
-- SUPERSEDED — Este archivo se ha consolidado en schema.sql.
-- ============================================================
-- Para nuevos despliegues, ejecuta solo `schema.sql` (incluye todo:
-- tablas, RLS, roles, festivos y funciones helper).
-- Este archivo se mantiene como referencia histórica únicamente.
-- ============================================================

-- Si vienes de una instalación antigua y necesitas migrar al esquema
-- nuevo, ejecuta `schema.sql` directamente — es idempotente y añadirá
-- lo que falte sin tocar tus datos.
